services:
  farm_assistant:
    container_name: farm_assistant
    build:
      context: .
    image: ghcr.io/pranavnbapat/farm_assistant:latest
    restart: unless-stopped
    env_file:
      - .env
